# Generated by Django 4.1.3 on 2022-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="day",
            field=models.CharField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default="Monday",
                max_length=9,
            ),
        ),
    ]
